### ISSUE TITLE
"xyz*" pattern produce a match even if the string does not start with xyz

### ISSUE THREAD

**Issue by 20iahazban** [becheran/wildmatch#1]
**Describe the bug**
"cat*" is a match for "wildcats", I think it only should match to "\*cat\*"

**To Reproduce**
println!("{}",WildMatch::new("cat*").is_match("wildcats"));

**Expected behavior**
WildMatch::new("cat*").is_match("wildcats")) --> false

**Desktop (please complete the following information):**
 - OS: win 10

**Comment by becheran** [comment]
Thank you very much. I fixed it with the latest release. Sorry for any inconvenience.

**Comment by 20iahazban** [comment]
thanks for the quick fix ;)
