### ISSUE TITLE
#[test_case("*32", "332")] fails

### ISSUE THREAD

**Issue by davehylands** [becheran/wildmatch#2]
**Describe the bug**
`*foo` should match any string which ends in `foo`.
`*32` detects a match in `432` but doesn't detect a match in `332`

**To Reproduce**
Add the following test cases:
```
#[test_case("*32", "432")]
#[test_case("*32", "332")]
```

Run `cargo test`

**Expected behavior**
Tests should pass

**Desktop (please complete the following information):**
 - OS: Mac OSX 10.15.4
 - Browser NA
 - Version NA

rustc -v reports
```
rustc 1.42.0 (b8cedc004 2020-03-09)
```

**Comment by becheran** [comment]
Thank you very much. I will provide a fix as soon as I can.
